name: Secrets
on: [workflow_dispatch]

jobs:
    build:
      name: Run Script
      runs-on: [Windows, x64, Self-hosted]
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: .\script.ps1
          shell: pwsh
          env:
            MyVariable: ${{ secrets.R7_API_PW }}
